export const states = [
  { abbreviation: "AL", name: "Alabama", id: 1 },
  { abbreviation: "AK", name: "Alaska", id: 2 },
  { abbreviation: "AZ", name: "Arizona", id: 3 },
  { abbreviation: "AR", name: "Arkansas", id: 4 },
  { abbreviation: "CA", name: "California", id: 5 },
  { abbreviation: "CO", name: "Colorado", id: 6 },
  { abbreviation: "CT", name: "Connecticut", id: 7 },
  { abbreviation: "DE", name: "Delaware", id: 8 },
  { abbreviation: "FL", name: "Florida", id: 10 },
  { abbreviation: "GA", name: "Georgia", id: 11 },
  { abbreviation: "HI", name: "Hawaii", id: 12 },
  { abbreviation: "ID", name: "Idaho", id: 13 },
  { abbreviation: "IL", name: "Illinois", id: 14 },
  { abbreviation: "IN", name: "Indiana", id: 15 },
  { abbreviation: "IA", name: "Iowa", id: 16 },
  { abbreviation: "KS", name: "Kansas", id: 17 },
  { abbreviation: "KY", name: "Kentucky", id: 18 },
  { abbreviation: "LA", name: "Louisiana", id: 19 },
  { abbreviation: "ME", name: "Maine", id: 20 },
  { abbreviation: "MD", name: "Maryland", id: 21 },
  { abbreviation: "MA", name: "Massachusetts", id: 22 },
  { abbreviation: "MI", name: "Michigan", id: 23 },
  { abbreviation: "MN", name: "Minnesota", id: 24 },
  { abbreviation: "MS", name: "Mississippi", id: 25 },
  { abbreviation: "MO", name: "Missouri", id: 26 },
  { abbreviation: "MT", name: "Montana", id: 27 },
  { abbreviation: "NE", name: "Nebraska", id: 28 },
  { abbreviation: "NV", name: "Nevada", id: 29 },
  { abbreviation: "NH", name: "New Hampshire", id: 30 },
  { abbreviation: "NJ", name: "New Jersey", id: 31 },
  { abbreviation: "NM", name: "New Mexico", id: 32 },
  { abbreviation: "NY", name: "New York", id: 33 },
  { abbreviation: "NC", name: "North Carolina", id: 34 },
  { abbreviation: "ND", name: "North Dakota", id: 35 },
  { abbreviation: "OH", name: "Ohio", id: 36 },
  { abbreviation: "OK", name: "Oklahoma", id: 37 },
  { abbreviation: "OR", name: "Oregon", id: 38 },
  { abbreviation: "PA", name: "Pennsylvania", id: 39 },
  { abbreviation: "RI", name: "Rhode Island", id: 40 },
  { abbreviation: "SC", name: "South Carolina", id: 41 },
  { abbreviation: "SD", name: "South Dakota", id: 42 },
  { abbreviation: "TN", name: "Tennessee", id: 43 },
  { abbreviation: "TX", name: "Texas", id: 44 },
  { abbreviation: "UT", name: "Utah", id: 45 },
  { abbreviation: "VT", name: "Vermont", id: 46 },
  { abbreviation: "VA", name: "Virginia", id: 47 },
  { abbreviation: "WA", name: "Washington", id: 48 },
  { abbreviation: "WV", name: "West Virginia", id: 49 },
  { abbreviation: "WI", name: "Wisconsin", id: 50 },
  { abbreviation: "WY", name: "Wyoming", id: 51 },
];

export const companies = [
  {
    id: "b5e8f9c4-8e02-469b-98d3-4c8f3e8b91f9",
    name: "My Company 1",
    logo: "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/company-logo-design-template-e089327a5c476ce5c70c74f7359c5898_screen.jpg?ts=1672291305",
    description: "",
  },
  {
    id: "e3f0d3d0-56a7-4b82-9e95-846e8f3c8f4a",
    name: "My Company 2",
    logo: "https://www.shutterstock.com/image-vector/circle-line-simple-design-logo-600nw-2174926871.jpg",
    description: "",
  },
  {
    id: "a2f5d3d9-7b5a-45f8-b8df-98c3e4b89a37",
    name: "My Company 3",
    logo: "https://st3.depositphotos.com/43745012/44906/i/450/depositphotos_449066958-stock-photo-financial-accounting-logo-financial-logo.jpg",
    description: "",
  },
];
